### ISSUE TITLE
Layout options

### ISSUE THREAD

**Issue by nullpainter** [mika76/mamesaver#16]
@andyvans was asking if there was an option to turn the titles off or change the font. Sounds like it could be a reasonable feature, particularly if you have some cool retro fonts.

So, perhaps another tab called 'layout' with:

1. System font list, defaulted 
2. Font size, defaulted 
3. Titles on/off checkbox, defaulted to on
4. Reset to defaults button 

What do you think? We could also include a colour picker, but I'm not convinced that it'd add much value.

**Comment by mika76** [comment]
I love it - sounds great - I was wondering though - do you think you could re-add the title screen as an option as well? I kinda like it 😊 and I think it's a nice Mame promotion...

**Comment by nullpainter** [comment]
Ha, sure! Can we compromise on the ten seconds though? It's an awfully long time to stare at a huge MAME logo 😆

**Comment by mika76** [comment]
🤣 for sure - you could even make that an option if you're adding an options screen hah

**Comment by mika76** [comment]
To make things easier - thinking of @andyvans idea - you could pop a property editor onto a tab and just have a whole bunch of settings in a class which gets serialized/deserialized. The options form might not have to be a big dev if you do that...

**Comment by mika76** [comment]
I really don't mind - whatever is easier for you guys - you guys are on a roll 😊

**Comment by nullpainter** [comment]
Makes a pleasant change from banking!

**Comment by mika76** [comment]
Funny, if I think back I was working at a Bank in South Africa when I first created this...

**Comment by nullpainter** [comment]
Since I will be adding a bunch more settings as part of this change, I was thinking of adding a settings XML file alongside the `gamelist.xml` file. What are your thoughts about me migrating the remainder of the settings to this file instead of from the registry? 

There's quite a lot of manual parsing and setting in `Settings.cs` and it may be quite a lot cleaner if it was just in a single XML document. I can retain population from the registry for any existing settings if this file doesn't exist.

No worries if you'd prefer basic options being in the registry. If you do, I may just tidy that class a bit to make it less verbose for setting and retrieving values.

**Comment by nullpainter** [comment]
>  I can retain population from the registry for any existing settings if this file doesn't exist.

Assuming there are more than just us three users, that is...

**Comment by nullpainter** [comment]
(comments about shifting away from registry deleted - I'll just tidy up the `Settings.cs` class a little)

**Comment by mika76** [comment]
Hey if serializing/deserializing an xml file is easier go for it - I don't mind - only thing is updates - but I don't think too many people are using this anyway so it's not a big issue

**Comment by nullpainter** [comment]
All covered by PR #18, which is good to go. I have tested it and written tests for the configuration stores and layout builder, but it would probably warrant a bit more of a workout.
