### ISSUE TITLE
Screensaver not always gracefully exiting

### ISSUE THREAD

**Issue by nullpainter** [mika76/mamesaver#27]
Particularly when jiggling mouse before MAME, an unhandled exception is thrown. This appears to be a recent regression and the unhandled exception handling doesn't appear to be catching it.

Feel free to assign this to me.

**Comment by nullpainter** [comment]
Have been unable to replicate, but suspect it may have been due to us not waiting for the MAME process to terminate before the screensaver exits. I have fixed this and added a bunch of other small fixes. Will create a single PR for these, #25 and #26.

**Comment by mika76** [comment]
Sweet 😊

**Comment by mika76** [comment]
Heh I've been playing around with the github Project and Milestone stuff - really cool!
