### ISSUE TITLE
Power options might not work when settings set to never turn off screen

### ISSUE THREAD

**Issue by mika76** [mika76/mamesaver#29]
From log
```
2018-09-06 11:55:00.468 +02:00 [INF] Connected to AC power; sleeping after 15372286728.091293 minutes
2018-09-06 11:55:00.477 +02:00 [ERR] Failed to run screensaver
System.ArgumentException: '-2147483648' is not a valid value for 'Interval'. 'Interval' must be greater than 0.
   at System.Timers.Timer.set_Interval(Double value)
   at Mamesaver.Power.PowerManager.Initialise()
   at Mamesaver.MameOrchestrator.Run()
```

My settings are set to never sleep and never turn off display (running in vm)...
![screen shot 2018-09-06 at 12 02 53](https://user-images.githubusercontent.com/229311/45150783-f237fb80-b1cc-11e8-9329-cc52e75446e2.png)

**Comment by mika76** [comment]
I will try debug this when I'm at my VS2017 machine...

**Comment by mika76** [comment]
I can confirm if I change the `turn off display` setting to 1 min, then Mamesaver works. Putting back to `Never` crashes again.

**Comment by nullpainter** [comment]
Oops, I also fixed this by making the `TimeSpan` nullable. Will create PR for you to look over. Having it nullable and only conditionally create the timer is a bit less hacky than using min/max value.

**Comment by nullpainter** [comment]
Actually, it'll end up with a merge conflict if I just create a PR. Here's my version of the fix:
https://github.com/nullpainter/mamesaver/commit/c9c42a44d6ba77a0990dd800611860990b5c7b3c

There's logging and no timer creation if there's no sleep configured.

**Comment by nullpainter** [comment]
Unrelated, but I also added some fixes suggested by VS code analysis in https://github.com/nullpainter/mamesaver/commit/ca5deae5ab42a8caea1fd916dfdaf0ea862bc420

**Comment by mika76** [comment]
Hey @nullpainter I'm happy to accept your fixes - is there some way I can add these manually? Can't you just merge master into your branch and overwrite  my changes?

**Comment by nullpainter** [comment]
Yep, I can do that. Probably be this evening though (so, in around six hours).

**Comment by mika76** [comment]
No stress - I'll be sleeping from now till then 🤣

**Comment by nullpainter** [comment]
All done. Sorry about that - I fixed it before I saw that you already had 😁 

btw, do you only have two games currently or are you worried about implied copyright issues?  Also - and hardly an issue (just me being a little OCD) - but the MAME icon looks a bit gross against your brown. Wondering whether the bog-standard Windows 10 colour scheme may look better for sample screenshots?

**Comment by mika76** [comment]
>All done. Sorry about that - I fixed it before I saw that you already had 😁

No prob at all - you were a little quiet so I thought you were busy and I would help you out a bit 😊 

>btw, do you only have two games currently or are you worried about implied copyright issues? Also - and hardly an issue (just me being a little OCD) - but the MAME icon looks a bit gross against your brown. Wondering whether the bog-standard Windows 10 colour scheme may look better for sample screenshots?

Hah it's my theme on my parallels VM - looks much better with the brownish background I guess. Yeah it's not the best. I wanted to include all the settings as screenshots and some demo ones too. I'll update when I get back to my other laptop - just been a bit busy to sit with it.

I only had 2 roms because I don't really use mame on my mac.

**Comment by nullpainter** [comment]
> No prob at all - you were a little quiet so I thought you were busy and I would help you out a bit 😊

Thanks; appreciated! Defects are shameful so I felt a moral responsibility to fix 😉

**Comment by mika76** [comment]
Watch out @nullpainter, that's how they get us! 😉 

I'll merge, sort out the releases and the screenshots some time today. Also time to update the website...
