### ISSUE TITLE
MAME configuration parsing fails when paths enclosed in speech marks

### ISSUE THREAD

**Issue by nullpainter** [mika76/mamesaver#34]
For example:

`rompath "roms;E:\MAME 0.195 ROMs (merged);E:\MAME 0.190 ROMs (merged)\MAME 0.190 ROMs"`

If enclosing speech-marks exist, they should be removed. The splitting code should also be taken out of `GameListBuilder` and split into a separate parser class so we can effectively write unit tests against it.

Additionally, this failure doesn't appear to result in any log entry being written.

@mika76, feel free to assign this to me.

**Comment by mika76** [comment]
Nice find...
