### ISSUE TITLE
Generic error message if ROM path not found

### ISSUE THREAD

**Issue by nullpainter** [mika76/mamesaver#35]
If an invalid ROM path is present in `mame.ini`, a generic dialog is displayed indicating that the path to MAME is incorrect. This should be changed to display the offending path in question.

**Comment by mika76** [comment]
'"roms;E:\MAME 0.195 ROMs (merged);E:\MAME 0.190 ROMs (merged)\MAME 0.190 ROMs (merged);E:\MAME 0.198 ROMs (split)"` seems to be the offending path

**Comment by nullpainter** [comment]
@mika76 that example is actually for #34 - this issue is just about a directory which doesn't exist.

**Comment by mika76** [comment]
ah 😊
