### ISSUE TITLE
Terminal flashes when game starts

### ISSUE THREAD

**Issue by nullpainter** [mika76/mamesaver#4]
The fix for this appears to be to set the `WindowStyle` when creating the MAME process to run the game:

```c#
ProcessStartInfo psi = new ProcessStartInfo(execPath);
psi.Arguments = game.Name + " " + Settings.CommandLineOptions;
psi.WorkingDirectory = Directory.GetParent(execPath).ToString();
psi.WindowStyle = ProcessWindowStyle.Hidden;
```

**Comment by mika76** [comment]
Unfortunately windowstyle.hidden did not work by itself but I think I found a way...

**Comment by nullpainter** [comment]
Interesting - it seems to do the trick for me on Windows 10.
