### ISSUE TITLE
Filter mechanical games, improve BIOS identification

### ISSUE THREAD

**Issue by nullpainter** [mika76/mamesaver#45]
As noted on [arcadecontrols.com](http://forum.arcadecontrols.com/index.php/topic,158313.0.html), mechanical games (i.e., fruit machines) shouldn't be included in the game list. 

I suspect we are implicitly filtering these anyway as the majority appear to only be partially emulated, however there is an `ismechanical` attribute for mechanical games in the `listxml` output, so it makes sense to filter by this.

There are also `isbios` and `isrunnable` flags so we should also check for these rather than just rely on the emulation status. Adding these checks pared down my list of games slightly, so clearly our status check wasn't quite good enough.

**Comment by mika76** [comment]
Good stuff - filtering the list is always good - it's so frustrating to run into the odd game that does not want to work in the screensaver...

**Comment by nullpainter** [comment]
Resolved by PR #46.
