### ISSUE TITLE
Mamesaver.scr - This application could not be started. Do you want to view information about this issue? ...

### ISSUE THREAD

**Issue by antdude** [mika76/mamesaver#52]
After downloading https://github.com/mika76/mamesaver/releases/download/3.0/Mamesaver.scr and moving into my updated 64-bit W7 HPE SP1's c:\windows\system32\, I couldn't configure and run it due to "Mamesaver.scr - This application could not be started. Do you want to view information about this issue? Yes No". I clicked yes and was taken to https://docs.microsoft.com/en-us/dotnet/framework/deployment/initialization-errors-managing-the-user-experience?version=(null)&processName=Mamesaver.scr&platform=0009&osver=5&isServer=0&shimver=4.0.30319.0 -- ".NET Framework initialization errors: Managing the user experience..."

**Comment by mika76** [comment]
Seems to me like it's struggling to run .net? Do you have.net framework 4.6 installed?

https://dotnet.microsoft.com/download/dotnet-framework/net462

**Comment by antdude** [comment]
How do I know what version I have installed? I know I have .NET, but which version(s)?

**Comment by antdude** [comment]
Paint.NET uses .NET, and it's fine.

**Comment by mika76** [comment]
Seems the latest paint.net uses 4.7. I would have thought that would work with mamesaver too. You could always try install 4.6 and see what happens. Shouldn't give a you any problems...

**Comment by mika76** [comment]
Or maybe you have an older paint.net with an older framework? Here Microsoft's instructions on how to determine which is installed : https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by antdude** [comment]
From my regedit.exe:

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client]
"Version"="4.7.02558"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"MSI"=dword:00000001
"Servicing"=dword:00000000
"InstallPath"="C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\"
"Release"=dword:000709fe

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client\1033]
"Version"="4.7.02558"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"Servicing"=dword:00000000
"Release"=dword:000709fe

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full]
"Version"="4.7.02558"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"MSI"=dword:00000001
"Servicing"=dword:00000000
"InstallPath"="C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\"
"Release"=dword:000709fe

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\1033]
"Version"="4.7.02558"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"Servicing"=dword:00000000
"Release"=dword:000709fe

**Comment by antdude** [comment]
I am using paint.net v4.1.6. BTW, I'm going to sleep soon.

**Comment by mika76** [comment]
Seems you have 4.7 which should run it without problems. Hmm I'll have to play around with it a bit and see if I can figure it out...

**Comment by antdude** [comment]
I was able to reproduce it in a clean, updated 64-bit W7 HPE SP1 in a virtual machine (VM) with VirtualBox. Its registry shows:

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client]
"Version"="4.6.01055"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"MSI"=dword:00000001
"Servicing"=dword:00000000
"Release"=dword:0006041f
"InstallPath"="C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client\1033]
"Version"="4.6.01055"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"Servicing"=dword:00000000
"Release"=dword:0006041f

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full]
"Version"="4.6.01055"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"MSI"=dword:00000001
"Servicing"=dword:00000000
"InstallPath"="C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\"
"Release"=dword:0006041f

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\1033]
"Version"="4.6.01055"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"Servicing"=dword:00000000
"Release"=dword:0006041f

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed says this is v4.6.1. :( Do you have an updated 64-bit W7 SP1? If not, then try it in a machine (virtual is fine to use since I reproduced it).

**Comment by mika76** [comment]
Hey try and place it in c:\windows\syswow64 and let's see if that's the issue... I'm pretty sure we compile for any cpu but who knows...

**Comment by antdude** [comment]
Woah. That worked! I'm configuring it now. I hope it works with old MAME v0.177. I haven't updated for years since I don't play games these days. :(

**Comment by mika76** [comment]
They changed the format of their xml output a while ago (don't know specific ver though) so if the build list function doesn't work then it's that and you'll probably need a newer version...

**Comment by nullpainter** [comment]
> Hey try and place it in c:\windows\syswow64 and let's see if that's the issue... I'm pretty sure we compile for any cpu but who knows...

I was just about to recommend that! I recall this issue before, but didn't pay much heed to it. We should verify that we are indeed compiling for `AnyCPU`, @mika76.

**Comment by antdude** [comment]
Darn it. I can't use MAME64 v0.177 since it didn't find any games. Boo! This will take a while for me to update my ROMs too. Bah!

**Comment by antdude** [comment]
I'm going to sleep! Thanks! ;)

**Comment by nullpainter** [comment]
I don't believe it would be too much effort for me to add support for earlier versions of MAME. What are your thoughts?

**Comment by antdude** [comment]
Nullpainter: Try it. Let's keep this one about .NET version issue. https://github.com/mika76/mamesaver/issues/53 for the older MAME version issue that I just made.

**Comment by nullpainter** [comment]
All fixed. PR submitted; will be in next release. The issue wasn't actually about .NET - it was that the screensaver was inadvertently being built as a 32 bit application. Thanks for reporting this, @antdude.

**Comment by antdude** [comment]
You're welcome. :D
