### ISSUE TITLE
Need to tell user to restart their MAME Saver after enabling its logging.

### ISSUE THREAD

**Issue by antdude** [mika76/mamesaver#55]
I assume it's the same for disabling it. I was wondering why my %TEMP%\MameSaver\ was missing in my 64-bit W7 HPE SP1 PC. :(

**Comment by mika76** [comment]
This is an ancient issue so I'm gonna close it - but also I'm not sure what it means - Mamesaver is a screensaver so it should not really be running while you're in the settings dialog...
