### ISSUE TITLE
MAME Saver v3.0.1's log file didn't roll over after 100 K in my 64bit W7 HPE SP1's %TEMP%\MameSaver\.

### ISSUE THREAD

**Issue by antdude** [mika76/mamesaver#56]
https://www.sendspace.com/file/dk0ahi for an example from https://github.com/mika76/mamesaver/issues/53#issuecomment-503953679. Nullpainter said it is supposed to make  another new log after 100 KB. Maybe don't set a limit size. Only make a new one each time MAME Saver is launched if its logging is enabled?

**Comment by mika76** [comment]
The logger seems to be configured properly so not sure what happened here. https://github.com/mika76/mamesaver/blob/8cc835cfa2de4852321dc6a8a8c323fc28c54a7a/Mamesaver/Program.cs#L108

Please reopen if it happens again.
