### ISSUE TITLE
Screensaver not working properly anymore since mame 0.223 (possibly earlier)

### ISSUE THREAD

**Issue by Solstar** [mika76/mamesaver#57]
Sicne mame 0.223, now the screensaver will forcibly shpow the "emulation/sound is not workingp ress any key to continue", obviously pressing any key will just quit the screensaver and goes back to Windows. For some weird reasons, only neogeo games are actually shown as attract mode screensaver, all the other games will just show this static screen and nothing else

**Comment by mika76** [comment]
Do you get the same issue when  you run mame directly? Could it be any of the arguments set on the settings page?

**Comment by Solstar** [comment]
yeah but only in mame64 (command line).does not happen with mameui, but that is not supported by the screensaver
--
Inviato da Libero Mail per Android Mercoledì, 28 Ottobre 2020, 08:39PM +01:00 da Mladen Mihajlović  notifications@github.com :

**Comment by mika76** [comment]
Only got to this now - but I just tried it with 0.259 and it works fine. Please reopen with more info if it happens again.
