### ISSUE TITLE
Error when used with MAME 0.227

### ISSUE THREAD

**Issue by VonSupponnatime** [mika76/mamesaver#58]
I installed Mamesaver v3, under configurations I changed the directory where MAME was located on my system, then tried to rebuild the game list under Game List and got this error:

Error running MAME; verify that the configuration is correct

I don't know if it's because the MAME executable went from being called MAME64 to just MAME, but that is the really the only thing I noticed that changed.  I even ran MAME by itself just in case there was a configuration file that had not been created that Mamesever needed to find.  I didn't change any of the command line options.

Thoughts?

**Comment by mika76** [comment]
Which version of mame are you using?

**Comment by VonSupponnatime** [comment]
I apologize, I incorrectly indicated 0.227 in the header of this email.
I'm actually using 0.232.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mika76** [comment]
Heh I finally checked this out - and tried it with the currently latest MAME 0.259 and it seems to be working fine. Maybe it was something in the actual MAME config which was broken? 

You can always turn on the Debug Logging checkbox in the settings and it should log any errors to `%LocalAppData%\Temp\Mamesaver\Logs` see [here](https://github.com/mika76/mamesaver#logging).
