### ISSUE TITLE
Artwork not showing

### ISSUE THREAD

**Issue by Jim0ne** [mika76/mamesaver#59]
I've been at this for a week. My Mame bevels (horizont and vertical) display fine whether from exe from within folder or cmd line but never from the screensaver. I've tried various command line options but none seem to read my mame.ini file. Is this not supported? I've tried to point to my -inipath, -fallback_artwork and -artpath in Command line options within the screensaver options but this doesn't work. On the other hand -video bgfx  and -brightness etc. do work. I'm doing 1080X1080 on a flipped 16:9 TV. I have searched for days but most posts are about filtering games and nothing about setting video options such as "small" or "large" which trigger bevels. Do I need a cmd line "Large" command in the Command line options for Mamesaver? Any help would be appreciated for this screensaver which is a vital part of my machine and cabinet. Thank you very much.

**Comment by nullpainter** [comment]
Thanks for reporting this and for your investigation. In order to get the game's information to display in the screensaver, I render an image and create a dynamic layout which uses this image. Unfortunately this was the only reliable way to get text appearing in an aesthetically pleasing fashion. The code to do this is in the [Layout](https://github.com/mika76/mamesaver/tree/master/Mamesaver/Layout) directory.

This is only enabled if the in game titles option is set, on the Layout tab. I haven't looked at Mamesaver for several years now, but try unticking this and seeing if things start to work for you.

**Comment by nullpainter** [comment]
(in other words, I replace whatever bezels are currently set and instead use a custom layout)

**Comment by Jim0ne** [comment]
Hello Matt,

Thanks for your reply, but I think it's a little different from my
situation. I'm not having a problem with text or screen stretching. It's
about the screen size and artwork. I'm not getting artwork to show up at
all. I can't believe with all the bezel artwork out there that no one else
has brought this up. I will have a look at the Layout
<https://github.com/mika76/mamesaver/tree/master/Mamesaver/Layout> directory
and look at the code to see what makes sense for my situation. I am all for
any kind of work around.

Thanks!

J

**Comment by Jim0ne** [comment]
Basically Mamesaver does not read the mame.ini file which is needed to
point to all art folders and files. If it works fine in cmd line, why not
in Mamesaver?

**Comment by mika76** [comment]
@Jim0ne Could you post the command line and ini file that you use that works?

**Comment by mika76** [comment]
Also as @nullpainter says:

> This is only enabled if the in game titles option is set, on the Layout tab. 

Turning this feature off should make mame use it's defined bezels, since it dynamically creates one for you if it's on. Mamesaver uses the bezel feature to show the game name while the game is playing.

**Comment by Jim0ne** [comment]
Thank you @nullpainter <https://github.com/nullpainter> !! That did it, one
click of a box on the layout tab to disable In-game titles. My arcade is
now complete. I highly recommend Mamesaver for anyone wanting to see real
arcade wait screens as opposed to downloaded video snaps. Thanks again for
your quick responses guys!
