### ISSUE TITLE
Not finding games

### ISSUE THREAD

**Issue by rodneylives** [mika76/mamesaver#60]
The screensaver doesn't seem to be finding available roms. Its list of games in setting is empty. It might have to do with them being stored outside of MAME's internal roms folder, but shouldn't the screensaver be able to find the rom collection from MAME's config?

I'm using Mamesaver 3.0, and MAME 244, on Windows 10.

I have tried it with MAME 200, with no difference.

Copying the files to MAME's roms folder, on the other hand, seems like it works. (It doesn't fail immediately, but puts its progress bar up for a while. I'll supply more information once its done building.)

**Comment by mika76** [comment]
Can you post your config file? Mamesaver get's the rom path from the config file so theoretically it should work fine... (https://github.com/mika76/mamesaver/blob/8cc835cfa2de4852321dc6a8a8c323fc28c54a7a/Mamesaver/Services/Mame/GameListBuilder.cs#L277)

**Comment by rodneylives** [comment]
Hmm... this might be part of it, I can't find the config file that MAME uses to save the ROMs directory. I thought it would be in ui.ini, but I can't find it there. And in fact, when I launch MAME and set the directory, test a game to make sure it works, then exit, when I restart it, it's back to using its default folder. Odd.

In case it matters: my MAME directory is C:\Games\mame200, and my roms directory is in a user directory, under C:\Users\(my account name)\ROMs\Arcade

**Comment by mika76** [comment]
Strange.

Mamesaver basically uses Mame itself to tell us the rom path (using the `-showconfig` argument https://docs.mamedev.org/commandline/commandline-all.html). Maybe try recreate the mame.ini file and see what happens.

**Comment by rodneylives** [comment]
Ah, I think I've discovered the problem, it was on my end. Thanks for your assistance!

**Comment by mika76** [comment]
@rodneylives glad you've sorted it - hope you enjoy Mamesaver 😊
